### ISSUE TITLE
Travis building time too long

### ISSUE THREAD

**Issue by Enchufa2** [r-simmer/simmer#11]
We should consider keeping a list of `r_binary_packages` in the Travis file to reduce the time required by this tool. For instance, the last build took about 10 minutes, while previous ones took about 2 minutes only. What do you think?

**Comment by bart6114** [comment]
I agree, I just updated the travis to be inline with the native R support on travis.

I'll update `.travis.yml` with the previously specified packages (+ `covr` as follows).

```
r_binary_packages:
    Rcpp
    R6
    magrittr
    dplyr
    tidyr
    ggplot2
    scales
    testthat
    knitr
    rmarkdown
    covr
```
