### ISSUE TITLE
Get_attribute/get_global not known in simmer 3.6.3

### ISSUE THREAD

**Issue by kgmuller** [r-simmer/simmer#112]
I get the error message

> get_attribute
Error: object 'get_attribute' not found

Has that function been removed?

**Comment by Enchufa2** [comment]
Are you sure that you are running v3.6.3? Is the package loaded?

**Comment by kgmuller** [comment]
Sorry, a NOOB mistake -- I was running 3.6.2. All is well!

Lo siento!

**Comment by Enchufa2** [comment]
No problem!

**Comment by kgmuller** [comment]
Sorry, I had 3.6.2 installed. Everything is ok in 3.6.3. 

 ¡Grazias por tu reaccion tan rapida!

Klaus G. Müller
