### ISSUE TITLE
redefine attribute

### ISSUE THREAD

**Issue by alexavdwaall** [r-simmer/simmer#113]
Dear Developer,

While trying to redefine a global attribute value, the following code produced some strange behaviour

patient_traj <- trajectory(name = "patient_trajectory") %>%
  set_global(key = "my_key", value = 123) %>%
  timeout(2) %>%
  set_global(key = "my_key", function() get_global(env, "my_key") + 800) %>%
  timeout(1);

env <- simmer() %>%
  add_generator("patient", patient_traj, function() rexp(1,1)) %>%
  run(until=5);
 
get_mon_attributes(env);
get_mon_arrivals(env);

When the last entry in `get_mon_attributes(env)' is 923, then rerunning the code produces 1723 instead of 923 as the redefined value of the `my_key' attribute. This does not occur when the last key value of the simulation is 923. 
Is this a bug in the source code?

regards, A.

**Comment by Enchufa2** [comment]
Note that you are drawing arrivals from an exponential distribution. Therefore, the output is not deterministic. You'll always obtain `123 + 800 * n`

**Comment by alexavdwaall** [comment]
Thank you for your reply. Maybe it is because of me misunderstanding what set_global does, but the exponential distribution does not make a difference when replacing it with a fixed arrival time.
Running the following twice gives 123 and 2*800+123 as attribute values:

env <- simmer() %>%
  add_generator("patient", patient_traj, function() 0.6) %>%
  run(until=4);
get_mon_attributes(env);

However, when the run time is 5 instead of 4 (see code below), and then running the code twice (or more)  always gives 123 and 923 as attribute values.

env <- simmer() %>%
  add_generator("patient", patient_traj, function() 0.6) %>%
  run(until=5);
get_mon_attributes(env);

One would generally expect that running an identical simulation with only deterministic distributions would give the same arrivals and their attributes. So maybe the attribute function is different than to what I think it is.

**Comment by Enchufa2** [comment]
There is a problem here with the scope of the variables. The trajectory calls the environment `env`, which means that it should be defined _before_ its use. But note that, when you run the following pipe:

```r
env <- simmer() %>%
  add_generator("patient", patient_traj, function() 0.6) %>%
  run(until=5)
```

`env` is assigned when the whole pipe is evaluated. In other words, `env` is defined when the simulation ends (!). So your trajectory is using the simulation environment from the _previous_ run. To avoid this, you should break the pipe whenever a trajectory uses the environment:

```r
env <- simmer() %>%
  add_generator("patient", patient_traj, function() 0.6)

env %>% run(until=5)
```

Check [this article](http://r-simmer.org/articles/simmer-03-trajectories.html#interacting-with-the-environment-from-within-a-trajectory) for further details.

**Comment by alexavdwaall** [comment]
Ah, that is a subtlety. Thank you for your response!
A.
