### ISSUE TITLE
Complete test coverage

### ISSUE THREAD

**Issue by Enchufa2** [r-simmer/simmer#12]
Working on it.

**Comment by bart6114** [comment]
at 97.19% ;)

**Comment by Enchufa2** [comment]
[This is the only file](https://coveralls.io/builds/4163534/source?filename=src%2FRcppExports.cpp) that reports lines without coverage, but I'm not sure if there's something we can do about them, as it is an auto-generated file...

**Comment by Enchufa2** [comment]
Mmmh... and `covr` reports a 100 % covered. It seems a kind of bug from the Coveralls side. So I consider it done.

**Comment by Enchufa2** [comment]
Ok, this wasn't a bug. What happened is that END_RCPP is a macro that encloses a `catch{}` block. So, now, I force some functions to fail with some tricks in order to get a complete coverage. 100 % :smile:

**Comment by bart6114** [comment]
Nice :)
