### ISSUE TITLE
Helpers for common activity patterns

### ISSUE THREAD

**Issue by Enchufa2** [r-simmer/simmer#124]
Some of these proposals should be implemented at a low level, some of them may be implemented as simple wrappers (in a separate package: [`simmer.bricks`](https://github.com/r-simmer/simmer.bricks)). Suggestions welcome (there's a [discussion thread on simmer-devel](https://groups.google.com/d/topic/simmer-devel/ONOkd0b4T_A/discussion)).

- Increment/decrement attribute (see #130)
- Timeout from attribute (see #129)
- Wait until a signal is received (already implemented in [`simmer.bricks`](https://github.com/r-simmer/simmer.bricks))
- Visit resource (already implemented in [`simmer.bricks`](https://github.com/r-simmer/simmer.bricks))
- ...

**Comment by harveymj** [comment]
Is there the possibility - either in the current edition or in the future - to delay the availability of a resource once it has been released? Thinking of the bank example, assume the customer completes their banking and leaves, but the manager needs to complete some paperwork before they can see the next customer, so the next person would still be in the queue. Is there a way to `trap` the resources?

**Comment by Enchufa2** [comment]
@harveymj This is a good one indeed! We were discussing exactly this recently [in the mailing list](https://groups.google.com/d/msg/simmer-devel/FhtpTAzerh4/doiZAHd5AgAJ). Now that you are revisiting it, I have refined what I proposed there.

Basically, my approach was to decrement the capacity of the resource right before releasing it. After some delay, another arrival would increment the capacity again. In that thread, I proposed another trajectory and another generator for this, but I've just realised that the `clone()` activity is just perfect for this, because it resembles parallel independent paths.

For example, following the bank example, let's say that the clerk's service time is 5, but they need an additional unit of time for paperwork after a customer leaves. This is how to do this:

```r
library(simmer)

bank <- trajectory() %>%
  log_("arrived") %>%
  seize("clerk") %>%
  log_("being attended") %>%
  timeout(5) %>%
  clone(
    2, 
    trajectory() %>%
      set_capacity("clerk", function() get_capacity(env, "clerk") - 1),
    trajectory() %>%
      timeout(1) %>%
      set_capacity("clerk", function() get_capacity(env, "clerk") + 1)
  ) %>%
  synchronize(wait=FALSE) %>%
  release("clerk") %>%
  log_("leaving")

env <- simmer() %>%
  add_resource("clerk") %>%
  add_generator("customer", bank, at(0, 0))

env %>% run() %>% invisible()
#> 0: customer0: arrived
#> 0: customer0: being attended
#> 0: customer1: arrived
#> 5: customer0: leaving
#> 6: customer1: being attended
#> 11: customer1: leaving
```

Note that the _main_ arrival decrements the capacity while the clone waits some time to increment it again. The `synchronize()` activity lets the main arrival continue and removes the clone.

So we can encapsulate this `clone > synchronize` sequence into a simmer _brick_ that we may call `delayed_release()`. The only problem is that this works only for non-preemptive resources. Preemptive resources require a slightly different implementation:

```r
library(simmer)

bank <- trajectory() %>%
  log_("arrived") %>%
  seize("clerk") %>%
  log_("being attended") %>%
  timeout(5) %>%
  clone(
    2, 
    trajectory() %>%
      release("clerk"),
    trajectory() %>%
      set_prioritization(c(.Machine$integer.max, .Machine$integer.max, 0)) %>%
      seize("clerk") %>%
      timeout(1) %>%
      release("clerk")
  ) %>%
  synchronize(wait=FALSE) %>%
  log_("leaving")

env <- simmer() %>%
  add_resource("clerk", preemptive=TRUE) %>%
  add_generator("customer", bank, at(0, 0))

env %>% run() %>% invisible()
#> 0: customer0: arrived
#> 0: customer0: being attended
#> 0: customer1: arrived
#> 5: customer0: leaving
#> 6: customer1: being attended
#> 11: customer1: leaving
```

Same general idea, but now the _main_ arrival releases the resource while the clone re-seizes it with maximum priority (so it will preempt any new seize if necessary).

So yes, we will see this `delayed_release()` as a helper in a future release. Thanks for the feedback!

**Comment by Enchufa2** [comment]
@harveymj There is an initial implementation of `delayed_release()` in the new package [`simmer.bricks`](https://github.com/r-simmer/simmer.bricks). To test it, you need to install it from GitHub along with the development version of `simmer`:

```r
if(!requireNamespace("remotes", quietly=TRUE))
  install.packages("remotes")
remotes::install_github(paste0("r-simmer/", c("simmer", "simmer.bricks")))
```

**Comment by harveymj** [comment]
@Enchufa2 Very cool. I will have a look at this asap. As always, thanks for all your help and willingness to implement new ideas.

**Comment by Enchufa2** [comment]
`simmer.bricks` is on CRAN, and all the proposals made so far were implemented. Closing this.
