### ISSUE TITLE
Travis says "missing config"

### ISSUE THREAD

**Issue by Enchufa2** [r-simmer/simmer#13]
[Check this](https://travis-ci.org/Bart6114/simmer/requests), please. Something was broken by adding the `r_binary_packages`. But I don't know what's the problem, because I tried even to restore the Travis file to its previous state and the "missing config" message still appears.

**Comment by bart6114** [comment]
hmzz I'm confused... weird; the eror means it can't find `.travis.yml` or that there is a misquotation or something in the file...

**Comment by bart6114** [comment]
removed a weird 'invisible' character and removed `covr` from binary packages list (not available)

after a slur of commits its succesfully building again ;)

ps. found this nifty tool: http://lint.travis-ci.org/
