### ISSUE TITLE
synchronize should be able to explicitly return the original

### ISSUE THREAD

**Issue by ay60** [r-simmer/simmer#132]
The `synchronize` option `wait = TRUE` should be modified to `all clones but the original are removed` rather than ` all clones but the first to arrive are removed`.  Otherwise this code does not work:

```
t <- trajectory() %>%
  seize("server",1) %>%
  clone(n = 2,
        trajectory("original") %>%
          timeout(1),
        trajectory("clone 1") %>%
          timeout(2)) %>%
  synchronize(wait = TRUE) %>%
  timeout(0.5) %>%
  release("server",1) 
```

But this one does:

```
t <- trajectory() %>%
  seize("server",1) %>%
  clone(n = 2,
        trajectory("original") %>%
          timeout(2),
        trajectory("clone 1") %>%
          timeout(1)) %>%
  synchronize(wait = TRUE) %>%
  timeout(0.5) %>%
  release("server",1) 
```

Which makes very little sense. The time spent in any of the parallel branches can be random. If we have no control over whether `synchronize` returns the original or not, we can lose resource locks at random.

Adding one more option to the `synchronize`, something like `wait_for_original = TRUE` is a viable solution as well.

**Comment by Enchufa2** [comment]
First of all, I'd like to point out that everything works as documented. So regarding "which makes very little sense"... it actually does, according to the documentation. ;-) Another question is whether the documented behaviour is appropriate or not.

The second thing I'd like to point out is that, with `wait = FALSE`, we find the same behaviour, but the *inverse problem*; i.e., the first trajectory works while the second one throws the error (*resource not previously seized*). All combined, this *symmetry*, conveys a sort of consistency so far. 

Now, for `wait = TRUE`, you argue in favour of waiting for the original (always or as an option), which breaks the symmetry: this *solves* this case, but nothing can be done for `wait = FALSE`. Moreover, it would introduce several technical problems that I'm unwilling to undertake if there's no good reason.

Nonetheless, I completely agree in one thing: we should be able to 1) seize a resource, 2) set `n` parallel random tasks, and 3) release the resource after all tasks are done. Well, in fact, we can! Let `n=2`, then the following trajectory always works:

```r
t <- trajectory() %>%
  seize("server", 1) %>%
  clone(n = 3,
        trajectory("original") %>%
          trap("signal") %>%
          wait() %>%
          wait() %>%
          untrap("signal"),
        trajectory("task 1") %>%
          timeout(function() rexp(1)),
        trajectory("task 2") %>%
          timeout(function() rexp(1))) %>%
  send("signal") %>%
  synchronize(wait = TRUE) %>%
  timeout(0.5) %>%
  release("server", 1) 
```

We let the clones perform the tasks, ensuring that the original one reaches the `synchronize` activity in the last place. Moreover, we can follow a similar strategy to solve the *inverse problem*, ensuring that the original arrival reaches the synchronization point in the first place:

```r
t <- trajectory() %>%
  seize("server", 1) %>%
  clone(n = 3,
        trajectory("original") %>%
          trap("signal"),
        trajectory("task 1") %>%
          timeout(function() rexp(1)),
        trajectory("task 2") %>%
          timeout(function() rexp(1))) %>%
  send("signal") %>%
  synchronize(wait = FALSE) %>%
  wait() %>%
  untrap("signal") %>%
  timeout(0.5) %>%
  release("server", 1)
```

And symmetry reigns again. :-)

**Comment by ay60** [comment]
Thanks @Enchufa2! That suggestion that you made actually works. I am new to simmer and I did not see yet the usefulness of the trap and signal before. It would be very helpful to see that example in the documentation. Somewhere the `Advanced Trajectory Usage` may be a good place to show the use case of a resource being locked before trajectory branching and unlocked after the branches join.

That said, I am still suggesting that the `synchronize` should have an explicit option to wait for the "original".  This is what would make sense to me, rather then just picking some of the branching threads at random. Simple things should be simple. This use case is one of the very basic ones.

**Comment by ay60** [comment]
I may have spoken too soon. The first suggestion that you provided works as long as there is only one resource. It fails if there are multiple resources.  Something like this works:
```
simmer(verbose = TRUE) %>% add_resource("server", capacity = 1) %>% add_generator("arrival", t, at(0,1,2,3)) %>% run()
```
But this one fails:
```
simmer(verbose = TRUE) %>% add_resource("server", capacity = 2) %>% add_generator("arrival", t, at(0,1,2,3)) %>% run()
```
The error is:
```
server: release: not previously seized
```

The second suggestion gives me unexpected results. The `server` is always getting released after 0.5 time units. That is, as if none of the branches have any effect on reaching the point of the server release. That may be the intent of that second example, but this is not what I am trying to achieve.

These are the first observations. I am trying to figure it out how to make it work right now.

**Comment by Enchufa2** [comment]
Yeap, you are right. My bad: I didn't try for multiple arrivals. Basically, the problem is the interaction between them. The restriction is that clones must signal the original arrival with the same name, but not others. Try this instead:

```r
signal <- function() get_name(env)

t <- trajectory() %>%
  seize("server", 1) %>%
  clone(n = 3,
        trajectory("original") %>%
          trap(signal) %>%
          wait() %>%
          wait() %>%
          untrap(signal),
        trajectory("task 1") %>%
          timeout(function() rexp(1)),
        trajectory("task 2") %>%
          timeout(function() rexp(1))) %>%
  send(signal) %>%
  synchronize(wait = TRUE) %>%
  timeout(0.5) %>%
  release("server", 1) 

env <- simmer(verbose = TRUE) %>% 
  add_resource("server", capacity = 2) %>%
  add_generator("arrival", t, at(0:3))

run(env)
```

This should always work fine, and the same for the other case.

> I am new to simmer and I did not see yet the usefulness of the trap and signal before.

I still keep discovering new uses of these verbs! They are quite versatile.

> It would be very helpful to see that example in the documentation. Somewhere the Advanced Trajectory Usage may be a good place to show the use case of a resource being locked before trajectory branching and unlocked after the branches join.

Agree. If we don't discover new issues, I'll add them right away.

> Simple things should be simple. This use case is one of the very basic ones.

Simple things should be simple, but I also think that APIs should remain clean and out of exceptions and corner cases. This is why I started a new package (under construction, not yet on CRAN) called [`simmer.bricks`](https://github.com/r-simmer/simmer.bricks) (see #124). Its purpose is to encapsulate common patterns such as the one we are discussing in this thread. Therefore, I think it could be a nice addition to `simmer.bricks`.

**Comment by ay60** [comment]
Thanks! That last variation seems to always work. I did not see it breaking yet.

If you will be adding that example to the documentation you can change the "server" to "room" and the parallel branches to "doctor" and "nurse". This is what I am trying to model: patient hospital visit. It can be a variation of your intro example.

**Comment by Enchufa2** [comment]
Perfect. Thank you for your help and your feedback!

**Comment by Enchufa2** [comment]
`simmer.bricks` is on its way to CRAN, and I've included [this](http://r-simmer.org/extensions/bricks/articles/introduction.html#parallel-tasks). Also, I've included a link to that in `simmer`'s _Advanced Trajectory Usage_ vignette.
