### ISSUE TITLE
Support shinysimmer?

### ISSUE THREAD

**Issue by harryprince** [r-simmer/simmer#138]
Is it someone want to build a debugging web application based on Shiny just like shinystan or tensorboard togather?

**Comment by Enchufa2** [comment]
A `simmer.shiny` package has crossed my mind several times already. But a proper solution would involve some new features in `simmer.plot` that ultimately depend on `DiagrammeR`. Moreover, as you can see in this issue tracker, there are some important enhancements pending for `simmer` too. 

All in all, I won't be working on a `simmer.shiny` package in a short-to-medium term.
