### ISSUE TITLE
How to distribute simulate queues with reinforcement learning?

### ISSUE THREAD

**Issue by harryprince** [r-simmer/simmer#139]
I am trying to train a reinforcement learning model (A3C), using a simulator engine like simmer, however, fail to find a best practice of the good simulator.

**Comment by Enchufa2** [comment]
Have you checked the vignettes? Specifically, take a look at [our paper](https://r-simmer.org/articles/simmer-02-jss.pdf), sections 3 and 4. Section 4.3 discusses best practices.

**Comment by Enchufa2** [comment]
BTW, for this kind of questions, please consider using the [simmer-devel mailing list](https://groups.google.com/forum/#!forum/simmer-devel). You'll benefit from a wider audience that may be able to help you.
