### ISSUE TITLE
Rcpp question

### ISSUE THREAD

**Issue by Enchufa2** [r-simmer/simmer#14]
I don't know if it is important, but it worries me [this line](https://github.com/Bart6114/simmer/blob/master/src/simmer_rcpp.cpp#L14) (and equivalent ones). Do you know the implications of putting here a true/false? Because, from the documentation, it is not clear to me.

**Comment by bart6114** [comment]
Strawled a bit through the Rcpp code and found this:

```
    /**
     * creates a new external pointer wrapping the dumb pointer p. 
     * 
     * @param p dumb pointer to some object
     * @param set_delete_finalizer if set to true, a finalizer will 
     *        be registered for the external pointer. The finalizer
     *        is called when the xp is garbage collected. The finalizer 
     *        is merely a call to the delete operator or the pointer
     *        so you need to make sure the pointer can be "delete" d
     *        this way (has to be a C++ object)
     */
    explicit XPtr(T* p, bool set_delete_finalizer = true, SEXP tag = R_NilValue, SEXP prot = R_NilValue)
```

So, I _think_ we can simply drop the `false` (and thus default to `true`) as a destructor for the `Simulator` class is defined anyway. I think initially I set it to false as I was assuming that the destructor would be called anyway when the instances lifetime was up (i.e. when the Rcpp process ended).

Have you tested the new codebase for mem leaks?

**Comment by Enchufa2** [comment]
Ok, understood. So we can drop the `false` from the Simulator creation, but it is necessary

**Comment by Enchufa2** [comment]
Ok, understood. So we can drop the `false` from the Simulator creation, but it is necessary in the activities (seize, release...), because we lose the pointer and they would be garbage-collected then.

I tested the code with valgrind and there are no leaks.
