### ISSUE TITLE
Is it possible to set attributes on resources, as well as on arrivals?

### ISSUE THREAD

**Issue by metanoid** [r-simmer/simmer#141]
Say we have two doctors, and one takes significantly longer to treat patients than the other.  We want to simulate a patient seizing the first available doctor, but then have a different timeout depending on which doctor was selected.  Is there a design pattern that allows for this?

**Comment by Enchufa2** [comment]
No, it's not possible to set attributes on resources.

To do that, you can set one trajectory per doctor, with different timeouts, and decide (with a branch) which path the arrival should follow based on the queue status, as [this example illustrates](https://groups.google.com/d/msg/simmer-devel/VbD7ZMX8WrI/TBxCMeI2CAAJ) (although probably the function to check the queues can be optimised, but the general idea is there).

**Comment by metanoid** [comment]
Alright, great, thanks!
