### ISSUE TITLE
Funny issue with resource

### ISSUE THREAD

**Issue by scotttetrick** [r-simmer/simmer#153]
I have a lot of resources in place, and my code has trajectories that have been pieced together.  But this error is perplexing.  My list TRAJ has a bunch of trajectories in them.

My trajectory:
```
DirectMem <- trajectory("DirectMem") %>%
  join(trajectory() %>% timeout(0),
       TRAJ[["RNF1-0.D->HNF7-4.U:REQ"]]) %>%
#  select(c("HNF7-4-1-1"),policy='random') %>%
  seize("HNF7-4-1-1",1) %>%
  log_("Got it") %>%
  join(trajectory() %>% timeout(0),
       TRAJ[["HNF7-4.D->SNF7-4.D:REQ"]],
       trajectory() %>%
         timeout(4) %>%
         seize("SNF7-4-2") %>%
         timeout(32) %>%
         release("SNF7-4-2") %>%
         timeout(4)) %>%
  clone(n=2,
        join(trajectory() %>% timeout(0),
             TRAJ[["SNF7-4.U->RNF1-0.U:DAT"]]),
        join(trajectory() %>% timeout(0),
             TRAJ[["SNF7-4.U->RNF1-0.U:DAT"]])) %>%
  synchronize(wait=TRUE,mon_all=TRUE) %>%
  join(trajectory() %>% timeout(0),
       TRAJ[["RNF1-0.D->HNF7-4.U:RSP"]]) %>%
  release("HNF7-4-1-1",1) %>%
  log_("Trying to release")

env %>% add_generator("TryA",DirectMem,at(0)) %>% run(1000) %>% 
  get_mon_arrivals(per_resource = TRUE,ongoing=TRUE)
```

When this is run, I get:
Error in run_(private$sim_obj, until) : 
  HNF7-4-1-1: release: not previously seized
In addition: Warning message:
In run_(private$sim_obj, until) :
  'TryA0': leaving without releasing 'HNF7-4-1-1'

How can my resource be simultaneously not seized and not released?

Thanks

**Comment by Enchufa2** [comment]
> How can my resource be simultaneously not seized and not released?

Obviously, by different arrivals. Arrival `TryA0` finished the trajectory without releasing, but this is permitted, so a warning is issued. Then another arrival hit a release without seizing before, and this is an error. So you'll have to revise your trajectories, because there's several wrong paths. BTW, if you use the current development version (which will be released on July), you'll get more info from the error.

Also please note that the `join` usage can be simplified:

```r
DirectMem <- trajectory("DirectMem") %>%
  join(TRAJ[["RNF1-0.D->HNF7-4.U:REQ"]]) %>%
  #  select(c("HNF7-4-1-1"),policy='random') %>%
  seize("HNF7-4-1-1",1) %>%
  log_("Got it") %>%
  join(TRAJ[["HNF7-4.D->SNF7-4.D:REQ"]] %>%
         timeout(4) %>%
         seize("SNF7-4-2") %>%
         timeout(32) %>%
         release("SNF7-4-2") %>%
         timeout(4)) %>%
  clone(n=2,
        TRAJ[["SNF7-4.U->RNF1-0.U:DAT"]],
        TRAJ[["SNF7-4.U->RNF1-0.U:DAT"]]) %>%
  synchronize(wait=TRUE,mon_all=TRUE) %>%
  join(TRAJ[["RNF1-0.D->HNF7-4.U:RSP"]]) %>%
  release("HNF7-4-1-1",1) %>%
  log_("Trying to release")
```

**Comment by scotttetrick** [comment]
found on  of the trajectories that I built up was not joined.


thanks

**Comment by Enchufa2** [comment]
Great, closing this then!
