### ISSUE TITLE
Handle unfinished arrivals

### ISSUE THREAD

**Issue by Enchufa2** [r-simmer/simmer#177]
Right now, there is no mechanism to handle unfinished arrivals:

- Arrivals dropped from a queue (when the queue size is shrinked and `queue_size_strict=TRUE`).
- Arrivals preempted from a server (when the capacity is shrinked or due to another higher-priority arrival, with `queue_size_strict=TRUE`).
- Leaving arrivals (from the `leave` activity).

A new mechanism is proposed to set a handler for them: a trajectory that would be followed after such events happen. See [this thread](https://groups.google.com/d/msg/simmer-devel/-KWhDnPuBSQ/U2Ch8U9UCAAJ) for further details.

Possible names for the new activity: `catch`, `cleanup`, `handle_exception`, `handle_unfinished`.

**Comment by thigger** [comment]
(continuing from simmer-devel thread linked above)
> There are already flags to show what happened. If the arrival was 
> preempted or dropped from a queue, get_mon_arrivals(per_resource=TRUE) 
> will show the seize event, and from the activity time you know whether 
> it was a preemption or a queue drop. If there is no info in such a 
> table, then the arrival left the trajectory using "leave". 

Are any of these accessible from within a trajectory during the simulation? I guess this might be a separate enhancement but I can't presently see any way of "knowing" whether a patient currently has a bed seized (for example). Even though the "seize" activity completed successfully, the bed may have been pre-empted away so it's now gone. (I'm trying to find a temporary workaround to my bed problem using signals, but I can't see how an arrival can "know" it's been put back in the queue)

I guess I'm looking for get_currently_seized(.trj, resource) which returns the amount of the resource currently seized or similar. And/or a getter to know which of the three situations you describe above have occurred (so I can branch down different trajectories). In my own project only the second will happen, but as you say it would be useful to have this generic.

**Comment by Enchufa2** [comment]
The problem is that, as soon as the arrival gets kicked from the resource, there is no amount seized, so a method such as `get_currently_seized` wouldn't help you.

An attribute could be easily used to distinguish between the `leave` case and the resource case. But I don't see right now an easy way to distinguish between a queue drop and a server drop.

Anyway, let's make this work in the first place and then we'll see how to address that.

**Comment by Enchufa2** [comment]
@thigger: There's an initial implementation in the `handle-unfinished` branch. Give it a try, please, to see if this works for you. I've tested the following:

```r
library(simmer)

rejected <- trajectory() %>%
  log_("I've been kicked")

patient <- trajectory() %>%
  handle_unfinished(rejected) %>%
  seize("bed") %>%
  timeout(10) %>%
  release("bed")

blocker <- trajectory() %>%
  set_queue_size("bed", 0) %>%
  set_capacity("bed", 0)

env <- simmer(verbose=TRUE) %>%
  add_resource("bed", preemptive=TRUE, queue_size_strict=TRUE) %>%
  add_generator("dummy", patient, at(0, 0)) %>%
  add_generator("blocker", blocker, at(5)) %>%
  run()
```

And it seems to work fine. The same if I change the patient trajectory with this one:

```r
patient <- trajectory() %>%
  handle_unfinished(rejected) %>%
  leave(1) %>%
  log_("Never reached")
```

**Comment by thigger** [comment]
Brilliant, thanks for the incredibly quick response - looks perfect and like it should work with my test project - I'm fairly locked down with R packages and compiling in the hospital but I should be able to try it when I get home.

For interest's sake - this is the [project](https://www.health.org.uk/improvement-projects/use-of-novel-modelling-techniques-and-routinely-collected-data-to-explore-responses-to)

**Comment by Enchufa2** [comment]
Very interesting project, thanks for sharing. Looking forward to seeing the results!

**Comment by thigger** [comment]
Just dropped it into my test project (still based on the bank example!) and it seems to be working as expected with no customers disappearing silently as they did before - thanks! Presumably it's safe to call handle_unfinished more than once in a trajectory as the patient moves around the hospital?

**Comment by Enchufa2** [comment]
Yes, it's safe. It just replaces the drop-out trajectory. If `NULL` is provided, it unsets the trajectory.

**Comment by thigger** [comment]
Brilliant, thanks - will that mean it's safe to call get_mon_arrivals etc during the simulation? (eg to help decide which trajectory to take)

**Comment by Enchufa2** [comment]
It's safe, but it's very inefficient (the whole table is copied to R for each call) and thus not recommended. That's why I opened #169.

**Comment by Enchufa2** [comment]
Related to this, #25 and #179 have been implemented.
