### ISSUE TITLE
Review TODO list

### ISSUE THREAD

**Issue by Enchufa2** [r-simmer/simmer#18]
The TODO list is a good long-term notepad. We should review it in order to determine which of those ideas make sense (and probably to add more). Then, we may decide which ideas we want implemented in the next release (along with the [rollback activity](https://github.com/Bart6114/simmer/issues/17) and [attributes](https://github.com/Bart6114/simmer/issues/16)) and, therefore, remove them from the TODO and open the corresponding issues.

For the time being, these are my two cents about the current TODO elements:
- _refine queue discipline (add priorities)_: Interesting feature implemented in all simulators. It seems easy to implement. +1 for the next release.
- _time-specific resource availability_: I would need a use case to understand this better.
- _add depletable resources_: The same than above.
- _stop the simulation mid-run, adjust some parameters and continue the simulation_: To me, it does not make sense, because a simulation should be automatic. I would need a good use case to change my mind.
- _create release_all event_: I think it isn't worth it. Too much complexity with no added value.
- _inspect the queue_: I don't understand this.

**Comment by bart6114** [comment]
My 2¢
- refine queue discipline (add priorities) = priority queue: should be implemented IMO
- time-specific resource availability = time schedule dependent resource capacity;  use case >

```
env <- simmer("SuperDuperSim") %>%
  add_resource("nurse", list(0=1, 30=2, 180=1) %>%  # time schedule dependent capacity
  add_generator("patient", t0, function() rnorm(1, 10, 2))
```

This allows to simulate work schedules, in this case there would be 1 nurse available from time 0 to 30, 2 nurses from time 30 to 180 and 1 nurse from 180 onwards. 
- add depletable resources: not necessary (simply don't release the resources)
- stop the simulation mid-run, adjust some parameters and continue the simulation: I follow you
- create release_all event: I follow you
- inspect the queue: a more advanced `peek` function which shows which events are in the queue (not a priority IMO)

**Comment by Enchufa2** [comment]
Perfect. So, wrapping up:
- Refine queue discipline: **New issue**.
- Time-specific resource availability: I understand now. **New issue**.
- Depletable resources: Delete.
- Stop mid-run: Delete.
- Release all: Delete.
- Inspect the queue: Keep in TODO for now.
