### ISSUE TITLE
enhance simmer transportation simulation by SUMO

### ISSUE THREAD

**Issue by harryprince** [r-simmer/simmer#185]
hi simmer team,
    SUMO is a great microscopic transportation simulator, I think simmer can consider being an adapter for SUMO, simmer is a great interface to define simulation.

* https://github.com/eclipse/sumo

**Comment by Enchufa2** [comment]
Thanks for the pointer, Harry. However, both `simmer` and `SUMO` have their own simulation engine, for different purposes, so `simmer` is not a good place for this. It would be better to build a dedicated interface in another package.

**Comment by harryprince** [comment]
@Enchufa2 the new interface is here:

https://github.com/ATFutures/sumor
