### ISSUE TITLE
Does anyone try simmer with keras as Deep Reinforcement Learning tool?

### ISSUE THREAD

**Issue by harryprince** [r-simmer/simmer#191]
simmer is pretty tidy than [gym](http://gym.openai.com) and [simpy](https://simpy.readthedocs.io/), wish to see someone play simmer with keras as Deep Reinforcement Learning tool.

**Comment by Enchufa2** [comment]
This is intended for bug reports and feature requests. Please, use the [mailing list](https://groups.google.com/forum/#!forum/simmer-devel) for general questions like this to reach a broader audience.
