### ISSUE TITLE
Simmer Simulate Jackson Network

### ISSUE THREAD

**Issue by harryprince** [r-simmer/simmer#192]
Does anyone implement Jackson Network Simulation in simmer ?

**Comment by Enchufa2** [comment]
This is intended for bug reports and feature requests. Please, use the [mailing list](https://groups.google.com/forum/#!forum/simmer-devel) for general questions like this to reach a broader audience.

**Comment by Enchufa2** [comment]
BTW, there's a vignette section about [queueing networks](https://r-simmer.org/articles/simmer-06-queueing.html#queueing-networks).
