### ISSUE TITLE
policy shortest-queue-available not selecting shortest queue

### ISSUE THREAD

**Issue by thigger** [r-simmer/simmer#196]
The policy "shortest-queue" seems to include server count
as well as queue size when deciding what's shorter.

eg
ward A - 20 patients being served (capacity 20), queue of 4
ward B - 30 patients being served (capacity 30), queue of 1

The policy chooses ward A despite the queue in ward B being shorter.

Enclosed a test scenario.

From simmer/inst/include/simmer/activity/resource_internal.h :

if (!selected || res->get_server_count() + res->get_queue_count() <
selected->get_server_count() + selected->get_queue_count())
selected = res;

[policy queue test - Copy.R.txt](https://github.com/r-simmer/simmer/files/3385841/policy.queue.test.-.Copy.R.txt)

**Comment by Enchufa2** [comment]
Thanks, you're right, this function should check whether there's availability in the server, but if not, it shouldn't include the server count in the decision.

As a workaround until the next release, you can provide your own R function implementing this policy.
