### ISSUE TITLE
Named rollbacks

### ISSUE THREAD

**Issue by Enchufa2** [r-simmer/simmer#197]
Current rollbacks (based on number of activities) are not ideal for prototyping, because they require an adjustment every time the user adds or removes an activity. This is even trickier when the trajectory is split into several pieces, or there are branches, etc.

It would be convenient to have some mechanism to label a point in a trajectory and then reference it by name. E.g., 

```r
trajectory() %>%
  timeout(1) %>%
  rollback_point("foo") %>%
  timeout(2) %>%
  timeout(3) %>%
  rollback("foo")
```

would be equivalent to

```r
trajectory() %>%
  timeout(1) %>%
  timeout(2) %>%
  timeout(3) %>%
  rollback(2)
```

**Comment by Enchufa2** [comment]
Discussion: https://groups.google.com/d/msg/simmer-devel/rcL6y4LwgfU/Vu2du8luEAAJ

**Comment by Enchufa2** [comment]
Hi, @Bart6114, I would like your input here. I think that the best way to implement this feature at a low level is to add an optional _tag_ or _label_ to activities that the `rollback` can read to set the target, and I wonder what's the best way to expose this. The one above is clear enough, but invites to think that `rollback_point` is yet another activity, and thus that the trajectories above are not exactly equivalent (length 5 and 4 respectively, which e.g. has implications for length-based rollbacks).

I'm considering other options such as

```r
trajectory() %>%
  timeout(1) %>%
  tag(timeout, "foo")(2) %>%
  timeout(3) %>%
  rollback("foo")
```

i.e. a labelling function that takes the generic and the tag and returns a closure that does the job, and its possible variations: maybe `tag("foo", timeout)` instead, or a shorter function name such as `.(timeout, "foo")`, etc.

Another option would be to extend the signature of all activities to include an optional tag. For example, now we have `timeout(.trj, task)`, which could become `timeout(.trj, task, ..., tag)`, and then we could do the following:

```r
trajectory() %>%
  timeout(1) %>%
  timeout(2, tag="foo") %>%
  timeout(3) %>%
  rollback("foo")
```

What do you think? Any other options?

**Comment by Enchufa2** [comment]
Another idea:

```r
trajectory() %>%
  timeout(1) %>%
  tag("foo")$timeout(2) %>%
  timeout(3) %>%
  rollback("foo")
```

which is easier to add to an existing trajectory and to move it around. @thigger your feedback is welcome too. :)

**Comment by Enchufa2** [comment]
This last idea can be tested in the `feature/rollback_tag` branch.

**Comment by Enchufa2** [comment]
> Another option would be to extend the signature of all activities to include an optional tag. For example, now we have `timeout(.trj, task)`, which could become `timeout(.trj, task, ..., tag)`, and then we could do the following:
> 
> ```r
> trajectory() %>%
>   timeout(1) %>%
>   timeout(2, tag="foo") %>%
>   timeout(3) %>%
>   rollback("foo")
> ```

This can be tested in the `feature/rollback_tag_arg` branch.

**Comment by Enchufa2** [comment]
I think I'm gonna go with this last option.

**Comment by thigger** [comment]
Apologies, been clinical and not keeping an eye - yes this is brilliant, thank you!
