### ISSUE TITLE
Refine resource's queue discipline

### ISSUE THREAD

**Issue by Enchufa2** [r-simmer/simmer#20]
- Add priorities.
- Preemption?

**Comment by bart6114** [comment]
ideally different levels of priorities
where a higher "level number" equals a higher priority

e.g.

```
t0<-
  create_trajectory() %>%
  seize("operator", 1, priority=2) %>%
  timeout(3) %>%
  release("operator", 1)
```

**Comment by bart6114** [comment]
woops, didn't mean to close it :grimacing:

**Comment by bart6114** [comment]
check https://github.com/Bart6114/simmer/blob/c3007cfc4adedd5fd9a857199bd0f0570859cace/tests/testthat/test-simmer-resource.R for an example

**Comment by Enchufa2** [comment]
Nice! BTW, merge the latest developments of the master branch in your tree, please. For instance, I introduced the Boost library and I created [a new header](https://github.com/Bart6114/simmer/blob/master/src/simmer.h) devoted to standardise the use of efficient containers (vector, queues, map, set...) through macros.

**Comment by bart6114** [comment]
nice^2

I'll try to do the merge this evening

**Comment by bart6114** [comment]
check 8a23121 for a start with testing FIFO processing (and implementation)

**Comment by bart6114** [comment]
moved compare func into the struct (tx, a lot more elegant) e2d28227

haven't had time to look into in in detail but couldn't get your suggestion working on the _simple_ FIFO ordering when priorities are equal (for example, std::sort also doesn't guarantee preserving order of equal elements).

**Comment by Enchufa2** [comment]
You are right. Definitely, we need the `arrived_at` secondary key (and my tests suggest that the priority queue performs similarly to the previous FIFO queue :+1:). As a consequence, I had to use priorities to ensure that releases go before seizes (see https://github.com/Bart6114/simmer/commit/ac74e22bf6f52f7ad8d1be075e98d0619aab3656 and [this test](https://github.com/Bart6114/simmer/blob/ac74e22bf6f52f7ad8d1be075e98d0619aab3656/tests/testthat/test-simulation-2.R)).

Now, what about preemption? It is a far more complex task. :grimacing: I'm going to merge the current changes into the master branch before continuing with this.

**Comment by bart6114** [comment]
Let's close this and discuss the preemption (which will be a far bigger challenge :grinning:) in #34
