### ISSUE TITLE
Waiting times per resource

### ISSUE THREAD

**Issue by xanmaas** [r-simmer/simmer#213]
I have a question regarding the waiting and arrival times per resource. Is there a way to get the time at which each item is being helped or is there a way so I can get a quick overview o the waiting times for each item per resource?

**Comment by Enchufa2** [comment]
See `?get_mon_arrivals`. There's a parameter, `per_resource=TRUE`, to obtain arrival statistics per resource. Then, `waiting_time = end_time - start_time - activity_time`.
