### ISSUE TITLE
Pulling instead of pushing

### ISSUE THREAD

**Issue by andreamordini** [r-simmer/simmer#215]
Hi all,
I am trying to simulate a fabrication and erection process in the construction industry.
Construction elements are created by resources and stored in a storage space. So far I can manage.
From the storage, the elements are pulled (not pushed) according to the construction programme (known).
Therefore, the elements do not stay a specific time in the storage but as long as they are called from the site.
How can I model this?

Thanks
Andrea

**Comment by Enchufa2** [comment]
See the section about asynchronous programming in the [JSS paper](https://r-simmer.org/articles/simmer-02-jss.pdf) (page 14) and the examples in the reference page for [interarrival communication](https://r-simmer.org/reference/send.html). Your items can `seize` some storage area and then `wait` until they receive a signal.

**Comment by Enchufa2** [comment]
Also, the [mailing list](https://groups.google.com/forum/#!forum/simmer-devel) is probably a better place for this kind of questions, because you have a broader audience there. :)
