### ISSUE TITLE
fifo or lifo

### ISSUE THREAD

**Issue by xanmaas** [r-simmer/simmer#216]
Is there a way to change the priority of an seize object from fifo to lifo? I could not find any info on this topic in the references.

**Comment by Enchufa2** [comment]
No, queues are always FIFO. But they are priority queues too, so you can set an increasing priority to the arrivals and you get a LIFO.

**Comment by xanmaas** [comment]
Thanks for the answer, but how can I set these priorities with an increasing order? I found it very hard to understand the example about setting the priority

**Comment by Enchufa2** [comment]
I would do something along these lines:

```r
t <- trajectory() %>%
  set_global("resource A", 1, mod="+") %>%
  set_prioritization(function() c(get_global(env, "resource A"), -1, -1)) %>%
  seize("resource A") %>%
  ...
```

The first activity increments a global counter for "resource A", and the second activity assigns this value. Subsequent arrivals get a higher priority, so you are simulating a LIFO.
