### ISSUE TITLE
Rollback activity: infinite loop

### ISSUE THREAD

**Issue by bart6114** [r-simmer/simmer#22]
Some ponderings; maybe it should be possible for a `rollback` to be infinite, only to be interrupted by the simulation end or a (currently none-existing) `skip(times)` activity. If https://github.com/Bart6114/simmer/issues/16 would be realised this would allow for a huge amount of flexibility.

**Comment by Enchufa2** [comment]
+1000

**Comment by Enchufa2** [comment]
Done. Now, you can implement an infinite rollback as follows:

``` r
t0 <- create_trajectory() %>% 
  timeout(function() 1) %>%
  rollback(1, times=Inf)
```

Or, alternatively, you can do the same as follows:

``` r
t0 <- create_trajectory() %>% 
  timeout(function() 1) %>%
  rollback(1, check=function() 1)
```

By specifying the `check` argument as a function, the `times` argument is ignored and the rollback activity decides whether to go back or not using this user-defined function, which has great flexibility (and a lot more when https://github.com/Bart6114/simmer/issues/16 is implemented).
