### ISSUE TITLE
Supporting H2/H2/1 HE2/HE2/1 advanced QS 

### ISSUE THREAD

**Issue by othmane-kada** [r-simmer/simmer#223]
![Screenshot from 2019-11-18 13-01-43](https://user-images.githubusercontent.com/45651554/69038650-b1a85480-0a03-11ea-8022-986507d1a61b.png)

hi, i wanted to know if there is a possibility to simulate a queuing system , witch has an hyper-expenential or hyper-Erlang arriving  function ? 
i wrote this for hyper_erlang but i dont get the results needed  for average waiting time ((

```r
tlmda=0.1
c=4
p=(1/2)+sqrt(((2*(1+c))-3)/(8*(1+c)))
lambda2=(2*(1-p))/tlmda
lambda1=(2*p)/tlmda
mu=1
m.queue <- trajectory() %>%
  seize("server", amount=1) %>%
  timeout(function()  rexp(1, rate=mu)) %>%
  release("server", amount=1)
mm1.env <- simmer() %>%
  add_resource("server", capacity=1, queue_size=Inf) %>%
  add_generator("arrival", m.queue, function() (p)*rgamma(1, shape=2, rate=lambda1))%>%
  add_generator("arrival2", m.queue, function() (1-p)*rgamma(1, shape=2, rate=lambda2))%>%
  run(until =1000000, progress=progress_bar$new()$update, steps = 1)

a=get_mon_arrivals(mm1.env)%>% 
    transform(waiting_time = ifelse ((end_time - start_time - activity_time)<0,0,(end_time - start_time -activity_time) ))
mean(a$waiting_time)
```

**Comment by Enchufa2** [comment]
Yes, you can, it's just a matter of defining the correct distribution functions. Comments:

- You have defined an exponential service time.
- Why are you defining two independent generators?
- What's the expected result?

**Comment by othmane-kada** [comment]
![Screenshot from 2019-11-18 15-32-42](https://user-images.githubusercontent.com/45651554/69049177-b4fa0b00-0a18-11ea-843a-df7ca743cd9a.png)
this is the task ,
a(t) :is the arrivals
b(t) : servicing
i already made the mathematical solution to find the average waiting time , 
now with Simmer i want to make a simulation for this system and calculate the waiting time and compare it to my mathematical results ,
im having difficult in finding the distribution function of my system :(

**Comment by Enchufa2** [comment]
But these are the PDFs. To sample from any distribution, you need to implement rejection sampling or, better, since you can calculate the CDF, inverse transform sampling. Or check if any package does this already for you. For example, you could try the `rherlang` function from the `mapfit` package.

**Comment by othmane-kada** [comment]
@Enchufa2  using rherlang its the first what i used , i  didnt got good results , when the system is low loaded rho=0.1 its gave me the same results but when the rho =0.5 0.9 highly loaded system it was the same results as 0.1 witch is from my point of view wrong , and also hypererlang its a heavy tailed , but i didnt saw that in results , maybe im wrongly writing codes , but i tried a lot before writing here for help 
+ when  i used the mm1  using exp function i had the same result in mathematic way and in Simmer too 
thats how i wrote it for erlang 

  library(simmer)
  library(progress)
  library('mapfit')
  
  set.seed(1234)
  
  mu <- 1
  lambda1=5
  lambda2=5
  p=0.1
  (param2 <- herlang(shape=c(2,2), mixrate=c(p,1-p),
                     rate=c(lambda1,lambda2)))
  m.queue <- trajectory() %>%
    seize("server", amount=1) %>%
    timeout(function()  rexp(1, rate=mu)) %>%
    release("server", amount=1)
  
  he2m1.env <- simmer() %>%
    add_resource("server", capacity=1, queue_size=Inf) %>%
    add_generator("arrival", m.queue, function() 4*rherlang(n=1, herlang=param2)) %>%
    run(until =100000, progress=progress_bar$new()$update, steps = 10)
  
  a=get_mon_arrivals(he2m1.env)%>%
    transform(waiting_time = end_time - start_time - activity_time) 
  mean(a$waiting_time)

**Comment by Enchufa2** [comment]
Check the notation. The `rate` parameter in the `herlang` function is equal to `2*lambda` in the equation you showed above. And thus you don't need to multiply by 4 the output from `rherlang`.

**Comment by Enchufa2** [comment]
Anyway, `simmer` has clear interfaces to define the arrival distribution and the service distribution, and with the correct ones, you should obtain the expected results.

This issue is a matter of how to define those distributions, which is beyond the scope of `simmer`. If you still have trouble using `mapfit::rherlang`, I suggest to contact the maintainer of that package. And for general questions about how to draw samples from a given theoretical distribution, probably StackOverflow or Cross Validated are better places.
