### ISSUE TITLE
Some book on simmer

### ISSUE THREAD

**Issue by AtharKharal** [r-simmer/simmer#225]
Is there book published or being written for a novice like me to fully appreciate the great work of simmer?

**Comment by Enchufa2** [comment]
There is no book yet. The [JSS paper](https://www.jstatsoft.org/article/view/v090i02) is the most comprehensive guide to date, together with the rest of [vignettes available](https://r-simmer.org/articles/).

**Comment by AtharKharal** [comment]
In fact till now, it appears, only queueing application are possible in simmer. Where one can find non-queueing DES using simmer?

**Comment by Enchufa2** [comment]
In general, most DES applications are somehow resource-constrained (not necessarily with queues), and thus that's the main focus of simmer. But, for instance, asynchronous events through a simple message-passing system (send-trap) is another cool feature. This is a general framework, and even though we put a strong focus on those resource-constrained use cases, I believe there are lots of possibilities. What kind of application did you have in mind?

**Comment by AtharKharal** [comment]
Examples may be like inventory, manufacturing, land use, urban sprawl and (might-be !) Monte-Carlo etc.

**Comment by Enchufa2** [comment]
Logistics and manufacturing are typical resource-constrained problems, so simmer is perfect for them, and many of the examples you may find in the documentation are appropriate. Spatial problems... it depends. Usually, they involve some kind of continuous model that is evaluated at regular intervals, and DES is not appropriate for this kind of dynamical system. Finally, Monte Carlo simulation is not DES, it's a different kind of simulation for a different kind of problems (see the [taxonomy](https://r-simmer.org/slides/20191115_xijur_simmer#4) defined by Law and Kelton (2000)).

**Comment by AtharKharal** [comment]
This would be nice if all major use-cases of simmer are collected in one document/book.

**Comment by Enchufa2** [comment]
Until then, any textbook on DES, such as Banks (2005), has a compendium of use cases that apply to simmer too.
