### ISSUE TITLE
New feature: renege_conditional()

### ISSUE THREAD

**Issue by s-geissler** [r-simmer/simmer#234]
New `renege_conditional(.trj, condition, out, ...)`, equivalent to `renege_if()`, but triggered by the outcome of a function provided as `condition` that returns `True` or `False`. On `True`, the arrival immediately (or after completing trajectory provided via `out`) abandons the trajectory.

Useful in cases that require abandoning arrivals based on global system state.

```
... %>%
renege_conditional(function() {get_global(env, "someState") > threshold}) %>%
...
```

**Comment by Enchufa2** [comment]
This is exactly what `leave` does. :) In fact, it does more things, because it expects some probability. But if you just return TRUE or FALSE (i.e., 1 or 0), then you have this exact use case.

**Comment by s-geissler** [comment]
Oh well - I could have gotten that myself. Thanks!
