### ISSUE TITLE
R-simmer restart vs resume

### ISSUE THREAD

**Issue by IoannaChr** [r-simmer/simmer#235]
I am trying to make a code in simmer using restart=FALSE and restart=TRUE in the add generator in order to see what is the effect of using restart and what is the effect using resume (I also add preemptive=TRUE in the add resource function). However, the results turn out to be the same which is not true in reality. Should I better use it in the trajectory in order to have the proper results?

**Comment by Enchufa2** [comment]
That option makes a difference only when preemption actually happens in your simulation. Could you please provide a short example of what you are trying to achieve?

**Comment by IoannaChr** [comment]
I am trying to simulate the arrivals of vessels in a port (barges and deep sea vessels) and in this scenario I am giving preemptive priority to the deep sea vessels and I see the effect of restart vs. resume. I wrote the following code for restart which eventually gave me a different result than the resume (in resume the only thing I changed is that I set restart=FALSE) but I am not sure whether my way of thinking is correct. 

```r
library(simmer)

set.seed(1269)

terminal <- simmer("terminal")

deepsea <-
  trajectory("Deep sea path") %>%
  log_("Here I am") %>%
  set_attribute("start_time", function() {now(terminal)}) %>%
  set_prioritization(c(1, 1, TRUE)) %>%
  seize("berth") %>%
  timeout(function() {rgamma(1,shape=2.53,scale=0.4)}) %>%
  #  log_(function() {paste("Waited: ", now(terminal) - get_attribute(terminal, "start_time"))}) %>%
  release("berth") %>%
  log_(function() {paste("Finished: ", now(terminal))})


barge <-
  trajectory("Barge path") %>%
  log_("Here I am") %>%
  set_attribute("start_time", function() {now(terminal)}) %>%
  set_prioritization(c(0, 0, TRUE)) %>%
  seize("berth") %>%
  #  log_(function() {paste("Waited: ", now(terminal) - get_attribute(terminal, "start_time"))}) %>%
  timeout(function() {rgamma(1, shape=1.24,scale=0.09)}) %>%
  release("berth") %>%
  log_(function() {paste("Finished: ", now(terminal))})

terminal <-
  simmer("terminal") %>%
  add_resource("berth",8,preemptive=TRUE) %>%
  add_generator("Deep sea vessel", deepsea, function() {c(0, rgamma(79, shape=1.47,scale=0.23))},priority=1,preemptible = 1, restart=TRUE) %>%
  add_generator("Barge", barge, function() {c(0, rgamma(609,shape=1.14,scale=0.04))},priority=0, preemptible=0, restart=TRUE) %>%
  run(until = 500)

scenario3_restart=terminal %>%
  get_mon_arrivals() %>%
  transform(waiting_time = end_time - start_time - activity_time)%>%
  transform (start_service_time= start_time + waiting_time)
```

**Comment by Enchufa2** [comment]
If you set `priority`, `preemptible` and `restart` in the generator, you don't need to use `set_prioritization` in the trajectory, because you are only rewriting your original choice (unless you want to change priorities, etc., dynamically, which I believe you don't here). Remove `set_prioritization` from your trajectories, then change `restart` and you'll see how your timings change.

**Comment by IoannaChr** [comment]
Yes initially I only used the priority and the restart=TRUE (or false in case of resume) in my add_generator but then the results of restart and resume turned out to be the same. Only when I added set_prioritization I was able to obtain different results (meaning that in the restart case the waiting time was higher, as I would expect).

**Comment by Enchufa2** [comment]
When I take your example as is, but removing `set_priorization`, the results are certainly different when I change `restart`. If you see no difference in other settings, it simply means that there's no preemption for the arrival processes and resources you defined.

**Comment by IoannaChr** [comment]
Thank you very much! I managed to make it work without the set_priorization after all
