### ISSUE TITLE
Problem with batch and branch and dynamic variables

### ISSUE THREAD

**Issue by DannyO-dev** [r-simmer/simmer#237]
Hello,
I'm struggeling with the functionality of batch and also with branch.
Let me try to explain my issues:

- The branch functionality is not working if I reach my condition with two arrivals at the same time. In this case my counter rises till the simulation time expires and I will not leave the branch.

Because of this I tried to batch my arrivals. But I don't know how many arrivals I will have at the same time, so I wanted to do it in a more dynamically way. This will bring me to the next point:

- The batch functionality is not working if I try to use a global variable. Only if I directly write a numeric value like batch(2).

I hope someone can assist me or maybe there is a better way for doing this...
Please see attached my sample code.
I am using the latest simmer version (# simmer 4.4.2).

Thank you in advance and best regards,
Daniel

![image](https://user-images.githubusercontent.com/70724692/92166527-09039e00-ee39-11ea-8c81-2fc7cfbce3a4.png)

**Comment by Enchufa2** [comment]
> * The branch functionality is not working if I reach my condition with two arrivals at the same time. In this case my counter rises till the simulation time expires and I will not leave the branch.

Could you please provide a short reproducible example of this? (In plain text, not a screenshot, please).

> * The batch functionality is not working if I try to use a global variable. Only if I directly write a numeric value like batch(2).

So it's working as documented. See `help(batch)`, `n` must be numeric.

**Comment by DannyO-dev** [comment]
Hello and thank you for the reply.
Because of the second one:
Why is this not working?

```r
library(simmer)

myList <- c(5, 11)
batchCount <- 0

elevator <- simmer()

drivingToDestination <- trajectory("Driving to destionation") %>%
log_("arrived") %>%
  log_(function() {
    batchCount <<- as.numeric(length(myList))
    paste("Batchsize:", batchCount)
  }) %>%
  
  batch(batchCount) %>%
  log_("in a batch") %>%
  timeout(5) %>%
  separate() %>%
  log_("leaving")
  
elevator <-
  simmer("elevator") %>%
  add_generator("drivingToDestination", drivingToDestination, at(0, 1))

elevator %>% run(until = 10)
```

I'm using a variable, and the value is numeric, but it doesn't work.
Is there another way to use the batch in a more dynamic way?
Thank you and best regards,
Daniel

**Comment by DannyO-dev** [comment]
And here is the example code for the first issue:

```r
library(simmer)

counter <- 0

elevator <- simmer()

drivingToDestination <- trajectory() %>%
  branch(
    function() counter != 5, continue = TRUE,
    trajectory() %>%
      log_(function() {
        counter <<- counter + 1
        paste("Current:", counter)
      }) %>%
      timeout(7) %>%
      rollback(3),
    
    trajectory() %>%
      log_("DUMMY for branch")) %>%
  
  log_(function() {
    paste("Done:", counter)
  })

elevator <-
  simmer("elevator") %>%
  add_generator("drivingToDestination", drivingToDestination, at(1, 1))

elevator %>% run(until = 30)
```

BR,
Daniel

**Comment by Enchufa2** [comment]
In the first issue, you are checking and incrementing the counter in different activities, and thus you get into trouble when there are simultaneous arrivals. That operation needs to be atomic, something like

```
checkCounter <- function() {
  check <- counter != 5
  if (check)
    counter <<- counter + 1
  check
}
```

in the branch, and then the increment in the next `log_` activity is not needed anymore.

About the second issue, simmer simply doesn't work that way. Dynamic arguments only work when a function is provided, but not all arguments in all activities accept a function as input. The `batch` activity requires a numeric as a first argument (fixed argument, doesn't change during the simulation) and doesn't accept a function at this moment.

**Comment by DannyO-dev** [comment]
OK got it...
Thank you very much!
