### ISSUE TITLE
Review- Gas station refuelling example

### ISSUE THREAD

**Issue by grnaveenkumar** [r-simmer/simmer#243]
Please  check the Gas station refuelling example in the simmer article.

The tank trunk is not able to refill the gas station.

https://r-simmer.org/articles/simmer-05-simpy.html#gas-station-refuelling-1

**Comment by Enchufa2** [comment]
As discussed in #239, this issue is present in the original SimPy example, and the purpose of the vignette is to mimic that behaviour. In the next release, there will be a note about this, implemented in this commit: https://github.com/r-simmer/simmer/commit/8b866a1f6ded2277c3dc4d77fdb7a85a6a9d3b19

**Comment by grnaveenkumar** [comment]
Thank you for your reply. Much appreciated. Very helpful.
