### ISSUE TITLE
Release the whole amount

### ISSUE THREAD

**Issue by Enchufa2** [r-simmer/simmer#25]
We should be able to do this:

``` r
t0 <- create_trajectory() %>%
  seize("dummy", 3) %>%
  timeout(1) %>%
  release("dummy") # releases 3
```

And, of course, this:

``` r
t0 <- create_trajectory() %>%
  seize("dummy", 3) %>%
  timeout(1) %>%
  release("dummy", 1) %>% # releases 1
  timeout(1) %>% 
  release("dummy") # releases 2
```

**Comment by bart6114** [comment]
+1 

Simple _shortcut_ off the top of my head; save the seized number as an attribute with an uncommon prefix. In the first example above set e.g. an attribute `___seized__dummy` with value `3` (in the background of-course). This can then be easily retrieved to release the correct amount. This does however incur an overhead (if you want to increment the seized amount you have to pass the `attributes` to the R side). Depending on the overhead incurred by monitoring the seized amount (in this shortcut style or by a robust c++ implementation), maybe only allow this from a given monitoring level.

In terms of syntax, it might require a different command like `release_all(resource)`. As `seize(resource)` defaults to an amount of `1` it isn't unlogical that `release(resource)` also defaults to an amount of `1`.

**Comment by Enchufa2** [comment]
I have plans for this. :wink: It should be managed by the resource itself. So I think it is best to reimplement the resource's server as a map of arrivals.

**Comment by bart6114** [comment]
Any educated guesses on how this would impact the run-time of larger simulations?

**Comment by Enchufa2** [comment]
It should be minimal because a map is similar to a hash table. It will be even smaller when we use an unordered_map from Boost or C++11 (this is in the TODO list).

**Comment by Enchufa2** [comment]
This is a good time to reopen this, because the enhancements implemented in the last year provide the required infrastructure to address it trivially.

Instead of changing `release("resource")` and `release_selected()`'s default `amount`, one solution would be to create another couple of verbs, `release_all("resource")` and `release_selected_all()`. But maybe `release_all()` is more intuitive for releasing the whole amount **in every resource** seized, which would be a nice addition too. For instance:

```r
traj <- trajectory() %>%
  seize("dummy1", 3) %>%
  seize("dummy2") %>%
  timeout(1) %>%
  release_all()
```

Feelings, @Bart6114?
