### ISSUE TITLE
create sensible $print functions for the different R6 classes

### ISSUE THREAD

**Issue by bart6114** [r-simmer/simmer#26]
_low priority_

consider:

```
> simmer()
<Simmer>
  Public:
    add_generator: function
    add_resource: function
    clone: function
    get_capacity: function
    get_generators: function
    get_mon_arrivals: function
    get_mon_attributes: function
    get_mon_resources: function
    get_n_generated: function
    get_queue_count: function
    get_queue_size: function
    get_resources: function
    get_server_count: function
    initialize: function
    name: anonymous
    now: function
    peek: function
    reset: function
    run: function
    step: function

  Private:
    mon_gen: NULL
    mon_res: NULL
    sim_obj: externalptr
```

a minimal example:

```
Simmer <- R6Class("Simmer",
  public = list(
    print = function() cat(paste0(
      "Simmer instance: ",self$name,"\n",
      "============================\n",
      "current sim time: ", self$now())),
    ....etc.....
```

which results in:

```
> simmer()
Simmer instance: anonymous
============================
current sim time: 0

```

**Comment by Enchufa2** [comment]
Some work on this: https://github.com/Bart6114/simmer/commit/9ee806e7df7d1e5635cf714d7ef448971b9a9f47. I don't know if you had in mind something... nicer. :smile: I didn't feel very... creative, so I confined myself to the trajectory output format.

Note: now `Trajectory$print()` points to `Trajectory$show()`, and therefore `create_trajectory()` and `create_trajectory() %>% show_trajectory()` do the same.

**Comment by bart6114** [comment]
It's already a lot better than the raw R6 show function :smile:

What about deprecating the `show_trajectory` function? As simply printing the object returns the same output, I don't really see use for the `show_trajectory` func.

**Comment by Enchufa2** [comment]
+1. How do we do that? Simply by specifying in the docs "(deprecated)"? Additionally showing a warning?

**Comment by Enchufa2** [comment]
Oh, [I see how it's done](http://r-pkgs.had.co.nz/release.html).
