### ISSUE TITLE
Seize activity shouldn't need to specify the amount

### ISSUE THREAD

**Issue by Enchufa2** [r-simmer/simmer#27]
Linking with https://github.com/Bart6114/simmer/issues/25, `seize("dummy")` should seize the whole resource, not one unit. Let's suppose that our _dummy_ resource has a capacity of 3. Then, `seize("dummy")` seizes 3. But if a previous arrival seized 1 and there is room for 2, then `seize("dummy")` stays in the queue until there is room for 3.

Wrapping up, I would maintain the syntax `seize`, `release`, but modifying the default behavior to be more natural:
- `seize("dummy")` = seize the whole resource.
- `release("dummy")` = totally leave the resource.

**Comment by bart6114** [comment]
If we go this route, this would break backwards compatibility as `seize("dummy")` currently seizes one dummy.

Therefor, I would be in favor of of upping the major version to 4 once this is implemented. While I'm not a big fan of upping the major version too often, I think we should do it when we loose backwards compatibility...

**Comment by Enchufa2** [comment]
Mmmh... you're right. Ok, let's postpone this for a major version change.

**Comment by Enchufa2** [comment]
Thanks for your feedback. Added to the TODO list.
