### ISSUE TITLE
get_mon_arrivals inhibited by a rollback ?

### ISSUE THREAD

**Issue by jr1234567** [r-simmer/simmer#326]
I continue my exploration of simmer package.
I notice that in the following simulation, uncommenting the rollback(2) in traj2 stops the get_mon_arrivals getting the arrivals. 

```
rm(list=ls())
library(simmer)

signal <- "Signal"

traj3 <- trajectory() %>%
  log_("executing the handler")  %>%
  set_attribute("TIME_interrupt", function() now(sim)) %>%
  timeout(2)

traj1 <- trajectory("Traj1") %>%
  trap(
    signal,
    handler = traj3, tag="piege", interruptible = TRUE) %>%
  timeout(60)

traj2 <- trajectory("Traj2")%>%
  send(signal) %>%
  timeout(function() 1)  # %>%
#   rollback(2)


################################################################################
sim <- simmer("Simulation")

sim %>%
  add_generator("Gen", traj1, at(c(0,2.5)), mon=2) %>%
  add_generator("SIGNALER", traj2, at(c(1, 2, 3, 20)), mon=2)


sim %>% run(40) 

arrivals  <- get_mon_arrivals(sim) 


```

**Comment by Enchufa2** [comment]
What do you mean? If no arrival finished a trajectory, no arrival can be reported.

**Comment by jr1234567** [comment]
Thank you
I wrongly expected that "arrivals" would summarize all entities "arriving" into the simulation, the column "finished" indicating whether the trajectory was finished.
Is there a function allowing to know *all* entities *entering* the simulation ?

**Comment by Enchufa2** [comment]
Did you check `get_mon_arrivals`' `ongoing` argument? ;-)

**Comment by jr1234567** [comment]
Sorry I missed it ! Thank you for pointing it and sorry for the noise !
