### ISSUE TITLE
don't return `run` invisibly

### ISSUE THREAD

**Issue by bart6114** [r-simmer/simmer#35]
Any specific reason why `run()` returns invisibly? 
I personally think the below should automatically call show/print (i.e. not return invisibly).

```
simmer() %>%
  add_resource("server") %>%
  add_generator("test", t0, at(0)) %>%
  run()
```

**Comment by Enchufa2** [comment]
Mmmh... not specially. I supposed that it could be desirable to be able to do something like this:

``` r
env %>% run(15) %>% onestep() %>% onestep()
```

or this:

``` r
env <- simmer() %>%
  add_resource("server") %>%
  add_generator("test0", t0, function() 1) %>%
  run(100) %>%
  add_generator("test1", t0, function() 2) %>%
  run(200) %>%
  del_generator("test0") %>%
  run(300)
```

**Comment by bart6114** [comment]
If we replace all - not only `$run()` -  `invisible(self)` with `self` in the `Simmer` R6 class we can still do this. And if it isn't saved in a variable it simply calls the `$print` function:

```
> simmer() %>% run(15) %>% onestep() %>% onestep()
Simmer environment: anonymous | now: 0 | next: Inf
```

and

```
> env<- simmer() %>% run(15) %>% onestep() %>% onestep()
> 
```

**Comment by Enchufa2** [comment]
Certainly. When you're right, you're right. :smile:
