### ISSUE TITLE
Need a function for multiple generations at a single time point, n_at

### ISSUE THREAD

**Issue by spgarbet** [r-simmer/simmer#43]
Please add an n_at function to the simmer library

If you need to generate multiple entities, all at the same time at the beginning of the simulation (or at any point), you can do that easily:

```
n_at <- function(n, t) {
  function() {
    if (n) {
      n <<- n - 1
      return(t)
    } else return(-1)
  }
}

env <- simmer() %>%
  add_generator("1000 at the beginning", t0, n_at(1000, 0))
```

**Comment by Enchufa2** [comment]
I was thinking... Maybe it's unnecessary, because you can use standard R functions for this. For instance, the example above can be rewritten as follows:

``` r
env <- simmer() %>%
  add_generator("1000 at the beginning", t0, at(rep(0, 1000)))
```
