### ISSUE TITLE
Implement error handling in plot_* functions

### ISSUE THREAD

**Issue by Enchufa2** [r-simmer/simmer#44]
The packages `dplyr`, `tidyr` and `ggplot2` are marked as _suggested_, because they are only used by `plot_*` functions, which are helper methods, just for exploratory purposes. 

Instead of simply failing when these packages are missing, it would be better to print a nice error message explaining these things.

**Comment by bart6114** [comment]
Something like below?

``` r
loadPlotDependencies<-function(){
  packages<-
    c("ggplot2","dplyr", "tidyr", "aPackageIDontHave")

  for(pkg in packages){
    if(!suppressWarnings(require(pkg, character.only = TRUE))){
      stop(sprintf('simmer\'s plotting functions depend on missing package "%s". Please install the package using: install.packages("%s")', pkg, pkg, call.=FALSE))
    }
  } 

}
```

``` r
> loadPlotDependencies()
Loading required package: aPackageIDontHave
Error in loadPlotDependencies() : 
  simmer's plotting functions depend on missing package "aPackageIDontHave". Please install the package using: install.packages("aPackageIDontHave")
```

**Comment by Enchufa2** [comment]
I was thinking of something like [this](https://github.com/topepo/caret/blob/ed81f1f6843b383a46697e082bb92fe7123b6b04/pkg/caret/R/modelLookup.R).
