### ISSUE TITLE
move demos in vignettes to demo/ folder

### ISSUE THREAD

**Issue by bart6114** [r-simmer/simmer#47]
If we move the in-vignette demo code to the `demo/` folder they can be included in the vignette using `knitr::read_demo` and/or `knitr::read_chunk`; see e.g. 8acd8437637d144052049cafb75b397057e25c5e.

This allows users to easily browse the `demo/` folder for examples. Non-vignette examples can be added to the `demo/` folder later on.

@Enchufa2, ok with this?

**Comment by Enchufa2** [comment]
Ok!
