### ISSUE TITLE
Package redesign

### ISSUE THREAD

**Issue by Enchufa2** [r-simmer/simmer#5]
I start this thread as an open channel to throw and discuss ideas. Some of them, down below.

I think it is important to maintain a Simulator class as simple as possible. Something like (brief Pythonic example)

``` Python
def run():
  initialisation()
  while (now < end):
    now, event = pop_event(queue)
    new_events = event()
    schedule(new_events)
```

and that's it. No possible errors.

But despite this, it would be great to preserve the current trajectory definition in R. Or something equivalent if you plan to rewrite this with R6 classes, but anyway I find this concept of _trajectory_ very flexible and powerful. However, maybe it would be desirable to substitute the current `add_entities_with_interval` with the concept of _generator_ of entities (something that works on demand, instead of instantiating `n` entities at the begining). Something like

``` R
t0 <-
  create_trajectory("my trajectory") %>%
  add_seize_event("server", 1) %>%
  add_timeout_event("rexp(1, 2)") %>%
  add_release_event("server", 1)

sim<-
  create_simulator("SuperDuperSim", n = 100) %>%
  add_resource("server", 1, queue_size=Inf) %>%
  add_generator(trajectory=t0, name_prefix="customer", interval="rexp(1, 1)")

sim <-
  sim %>%
  simmer(until=1000)
```

Yes, it is essentially the same syntax, but, internally, a generator is quite different. Note also that I moved the condition `until` into the `simmer()` call. This is because, with generators, we will be able to rerun the simulation multiple times with different `until` values.

Finally, instead of `add_skip_event`, I'd suggest a more convenient and visual syntax. I don't know, for instance...

``` R
t1 <-
  create_trajectory("trajectory with a branch") %>%
  ## add a branch (50 - 50 chance)
  add_branch_if("runif(1) > 0.5") %>%
    add_timeout_event(15) %>%
  add_branch_else() %>%
    add_timeout_event(5)
```

Probably this is not the best solution either, but at least the trajectory flow is more evident.

**Comment by bart6114** [comment]
I also like the trajectory approach, to me - but this might be related to what I primarily use the package for - working with a trajectory is very intuitive.

I wasn't a fan of the `add_skip_event` method, what do you think about the below options (seems easier to implement to me).

```
t1 <-
  create_trajectory("trajectory with a branch") %>%
  ## add a branch (50 - 50 chance)
  branch(
    list(
      prob=.5,
      trajectory={
        add_seize_event("server", 1) %>%
          add_timeout_event(15) %>%
          add_release_event("server", 1)
      }),
    list(
      prob=.5,
      trajectory={
        add_seize_event("server", 1) %>%
          add_timeout_event(15) %>%
          add_release_event("server", 1)
      })
  ) %>%
  ## here the branches are basically merged again
  add_timeout_event(5)
```

Ofcourse the `prob` parameter can be evaluated at runtime.

I feel the `add_` prefixes before all the methods are a bit redundant, I'm thinking about leaving them out.

**Comment by Enchufa2** [comment]
Regarding the branch syntax, much better, indeed. I agree also the `add_` prefix is redundant. :+1: 

And as we said by email, the tricky matter is where to cut, that is, what parts go to Rcpp. Because R is extremely slow basically doing one thing: allocating dynamic memory. As a result, we have to consider that
- A generator creates new entities on demand.
- An entity creates events during its lifetime.
- The monitoring code needs to store the system state at each point in time (each event occurrence), that is, it needs to grow numeric vectors dynamically.

Thus, those three things shouldn't be done in R.

BTW, as an exercise, I translated the Python example that I shared with you by email entirely to R6 classes (and it is extremmmmely slow compared to Python :D). I can share that code if it may help.

**Comment by bart6114** [comment]
you're always welcome to share the example (gist/mail) :+1:

**Comment by Enchufa2** [comment]
[Here it is!](https://gist.github.com/Enchufa2/9840cb001814ace28164) :-)

**Comment by Enchufa2** [comment]
I was trying to translate the trajectory concept with basic branching support to R6 classes. You can see the changes [here](https://github.com/Enchufa2/simmer/blob/dev/R/event.R) and [here](https://github.com/Enchufa2/simmer/blob/dev/R/trajectory.R). With that code, you can build a trajectory as follows:

``` R
t0 <- Trajectory$new("my trajectory") $
  seize("server", 1) $
  timeout(function() rexp(1, 1)) $
  branch(prob=0.1, merge=F, Trajectory$new("branch1") $
    seize("server", 2) $
    timeout(function() 1) $
    release("server", 2)
  ) $
  branch(prob=0.9, merge=T, Trajectory$new("branch2") $
    seize("server", 4) $
    timeout(function() rexp(1, 3)) $
    release("server", 4)
  ) $
  timeout(function() 1) $
  release("server", 1)
```

Internally, the trajectory grows a linked list of event classes. But this approach has a number of shortcomings. Specifically, how to start or end a trajectory with a branch is still unresolved. I don't know whether it is preferable to keep things simpler and go back to the `skip_event` approach.

But there are other kind of problems too. Suppose that, at some point in a trajectory, I want to jump to a branch (or skip events) if and only if a resource's queue holds a minimum number of customers, instead of some jump probability. We need access to that resource somehow in the trajectory.

**Comment by Enchufa2** [comment]
Ok, I completed a fully working version with R6 classes entirely. It is in [my dev branch](https://github.com/Enchufa2/simmer/tree/dev). You can test it with [these examples](https://github.com/Enchufa2/simmer/blob/dev/tests/dev.R). If you agree with the architecture, I can open a pull request and the next steps would be to 1) decide which parts are translated to C++ and 2) do it. :smile: 

BTW, roxygen2 does not support R6 classes yet. So the documentation of the classes' methods must be done manually.

**Comment by bart6114** [comment]
thx, looks very nice! I'll have a more detailed look at it this evening.

Do you see any direct issues with implementing the simpy/simjulia examples (https://github.com/BenLauwens/SimJulia.jl/tree/master/examples) using your codebase?

**Comment by Enchufa2** [comment]
I was experimenting with Rcpp and translating the core to C++. If you want to try the pure R6 version, checkout the following commit, please:

``` bash
git clone https://github.com/Enchufa2/simmer.git
cd simmer
git checkout 3b5bdbf3e9d44f50685e9b91f7a60e1945a4cfbe
```

Instead, if you try the HEAD of the repository, you will be running a preliminary and buggy C++ version (but more or less it works!).

I'll take a look at that simpy/simjulia examples.

**Comment by Enchufa2** [comment]
Bug found! The C++ translation is completed and fully functional (except for the parallelization). :smile:

**Comment by Enchufa2** [comment]
The package redesign is complete and I've added documentation and a lot of unit tests. Check my master branch, please (take your time), I think it is ready for a new release.

**Comment by Enchufa2** [comment]
I've got some feedback from my colleagues here at the university, avid users of other simulation environments. The primary issue they found is that arrivals cannot perform custom tasks and cannot interact with a more general system beyond the defined resources. I cannot but agree with them. Without that feature, _simmer_ cannot be called "discrete event simulator" but "queueing systems simulator" only.

The good news is that this feature is easy to implement. This will require two things:
- Mechanisms for the arrivals to retrieve information about the system status (additional calls to retrieve the occupancy of resources, etc.).
- A new activity called "task" intended to trigger custom functions.

An example of the latter:

``` R
t0 <- Trajectory$new() $
  seize("server", 1) $
  task(function() { do_something_here() }) $
  timeout(function() 1) $
  release("server", 1)
```

I can implement these changes now to incorporate them into the release 3.0.0 or we can release the current version and publish those improvements as 3.1.0. What do you think?

**Comment by paulorochasa** [comment]
How can i define multiple different generators during the simulation period? What i have is a patient admission rate that is different during the day and want to reflect that in the simulation genarators.

Thank you in advance.
BM
