### ISSUE TITLE
Change branch's 'merge' argument to 'continue'

### ISSUE THREAD

**Issue by Enchufa2** [r-simmer/simmer#57]
I was thinking, @Bart6114, that we chose a not-so-intuitive name for `branch`'s `merge` argument. It would be much better something like `continue`, but I don't see an easy way to change this without breaking compatibility. Any ideas?

**Comment by Enchufa2** [comment]
After some digging, this seems to work:

``` r
# roxygen documentation here
# @export
somefunc <- function(continue, x) {
  x * continue
}

# save the latter
somefunc.call <- somefunc
# intercept it
somefunc <- function(...) {
  # get call
  caller <- sys.call()
  # replace the function name
  caller[[1]] <- as.name("somefunc.call")
  # replace "continue" and show a warning if "merge" is found
  if ("merge" %in% names(caller)) {
    warning("'merge' is deprecated, use 'continue' instead")
    caller$continue <- caller$merge
    caller$merge <- NULL
  }
  # make the proper call
  eval(caller)
}

somefunc(continue=2, 3)
#> [1] 6
somefunc(2, 3)
#> [1] 6
somefunc(merge=2, 3)
#> [1] 6
#> Warning message:
#> In somefunc(merge = 2, 3) : 'merge' is deprecated, use 'continue' instead
```

What do you think?

**Comment by bart6114** [comment]
@Enchufa2, fully agree with the more intuitive naming.

What about the below snippet? 

``` r
branch <- function(traj, option, continue=merge, merge=continue, ...) traj$branch(option, continue, ...)
```

We could then simply add to the documentation that from version x, the support for the `merge` parameter would be dropped (and maybe show a warning).

**Comment by Enchufa2** [comment]
If you are ok with the renaming, I'd prefer my scheme above. The problem is that your snippet breaks backwards compatibility. With my example, however,
- The new parameter works.
- The unnamed call works.
- The old parameter works and shows a warning.

The documentation can still describe the old parameter, saying that from version x, the support for it would be dropped.

**Comment by Enchufa2** [comment]
Mmmmh... but my approach has problems with `magrittr` pipelines...

**Comment by bart6114** [comment]
What about the below? 

``` r
the_func<-function(new=old, old="_deprecated"){
  if(!old=="_deprecated") warning("use of 'old' is deprecated")
  new
}

# new param works
the_func(new=123)
# unnamed call works
the_func(123)
# old works and shows a warning
the_func(old=123)
```

Haven't compared it, but I think that this might also be more performant.

**Comment by Enchufa2** [comment]
There was a problem when the old param was used, but it's solved. Done, thanks!
