### ISSUE TITLE
Performance improvement: batched generation

### ISSUE THREAD

**Issue by Enchufa2** [r-simmer/simmer#65]
Until now, generators expect one interarrival value at a time in order to generate one arrival at a time. But it's perfectly possible (and more performant) to receive `n` interarrival values to generate `n` arrivals at a time. So instead of

``` r
add_generator("dummy", trajectory, function() rexp(1, 2))
```

it would be possible to do the following:

``` r
add_generator("dummy", trajectory, function() rexp(100, 2))
```

As a consequence, convenience functions could be improved. For instance, `at` could return all the values in one shot.

Finally, as a collateral benefit, if  we want to generate arrivals following some distribution, but in rows of `n`, we would be able to do the following:

``` r
add_generator("dummy", trajectory, function() c(rexp(1, 2), rep(0, n-1)))
```

**Comment by nacnudus** [comment]
This broke the hacky code I'd used in the Bank vignette (which I'm only just writing now, sorry).

```
customer <- 
  create_trajectory("Customer's path") %>%
  timeout(every(10, 7, 20))
```

which sets specific timeouts for three specific customers.  Admittedly that's not a compelling use case.  Is there an alternative to copying the original `every` code that created a function, i.e.

```
every <- function(...) {
    time_diffs <- c(...)
    i <- 0
    function() {        
      if (i < length(time_diffs)) {     
        i <<- i+1       
      } else {      
        i <<- 1     
      }     
      return(time_diffs[i])     
    }       
  }
```

**Comment by Enchufa2** [comment]
There is no alternative, sorry. `every` is deprecated and will be removed from the next release.
