### ISSUE TITLE
correlating arrival distributions

### ISSUE THREAD

**Issue by michaelsbradleyjr** [r-simmer/simmer#74]
My apologies if my inquiry is phrased a bit roughly. I've been experimenting with `simmer`, making attempts at functionality I'd like to achieve with my simulations, but I don't think I completely understand how all the pieces work, or could work, together.

I was hoping it would be possible within `dist` functions passed to multiple `add_generator` calls to check the output of `get_mon_arrivals` as the simulation rolls along. If an event of type `A` (i.e. an arrival for trajectory `A`) is ongoing, that may affect the probability that an event of type `B` or `C`, or `A` itself, occurs in an overlapping time period. But what I've found is that `simmer::now()` as reported in a `dist` function is somewhat ahead in time of the information obtained via `get_mon_arrivals`, such that it's always too late to make such an adjustment.

Perhaps my difficulty is related to #73?

**Comment by Enchufa2** [comment]
`simmer::now()` reports the current simulation time. `get_mon_arrivals` gets populated as arrivals finish their trajectories. So the information retrieved via `get_mon_arrivals` is in general behind the current simulation time.

Each time you call a `get_mon_`-something function, the data gathered by the simulator is copied from the C++ core to R, so these methods are intended to extract the final results, not to be called multiple times during the simulation.

I'm sure there must be another way to do what you are trying to achieve but without `get_mon_arrivals`. Could you provide us with a small example code, please?

**Comment by michaelsbradleyjr** [comment]
I will provide a code example of what I'm trying to do, but I'm not sure how to do so without the use of `get_mon_arrivals`, which, as you say, will not function correctly. So the example will be code that does not work.

In more direct prose than what I wrote previously:  let's say I want to generate three separate streams of events, `A`, `B`, `C`. The values returned by `dist` for each separate generator should be able to be affected (one way or another) according to whether or not there are unfinished events of the same or another type. Also, I badly need that things like timeout, attributes, etc. within a trajectory can be affected by whether or not there are one or more ongoing (unfinished) events.

**Comment by Enchufa2** [comment]
Let's say we have a generator called "A", so that it generates arrivals called "A0", "A1"... and so on. At any moment, the number of ongoing (unfinished) A events is

``` r
num_A_finished <- env %>%
  get_mon_arrivals() %>% 
  dplyr::filter(grepl("A", name)) %>% 
  nrow

num_A_unfinished <- get_n_generated(env, "A") - num_A_finished
```

But I discourage this method because it seems inefficient to me (I didn't test it though, maybe not as much as I think). You can also do the following instead:

``` r
num_A_unfinished <- 0

increment_A <- function() {
  num_A_unfinished <<- num_A_unfinished + 1
  return(0)
}

decrement_A <- function() {
  num_A_unfinished <<- num_A_unfinished - 1
  return(0)
}

traj_A <- create_trajectory() %>%
  timeout(increment_A) %>%
  # do A stuff here %>%
  timeout(decrement_A)
```

And at any moment, you keep the number of ongoing events in a global variable. For better performance, remove the increment from the trajectory and include that operation in the `dist` function.

If you test both methods, please tell us which is more efficient.

**Comment by michaelsbradleyjr** [comment]
Thank you, I will!
