### ISSUE TITLE
Create dummy functions for instantiating R6 classes

### ISSUE THREAD

**Issue by bart6114** [r-simmer/simmer#8]
For instantiating R6 classes a dummy function should be available. End-users shouldn't have to bother with the instantiation of the class (and thus the `$new()` aspect).

This can be done with minimal coding:

```
simmer<-function() Simmer$new()
```

Now we can simple call `simmer()` instead of  `Simmer$new()`

Again no improvement in terms of functionality, but eases usability a bit.

**Comment by Enchufa2** [comment]
And this definitely solves the documentation problems with R6 classes, so I totally agree with this approach.

**Comment by Enchufa2** [comment]
Done!
