### ISSUE TITLE
Global attributes

### ISSUE THREAD

**Issue by Enchufa2** [r-simmer/simmer#82]
@Bart6114, please review this issue.

It seems that in some cases it could be interesting to define and monitor global attributes. Should we consider this addition?

If we go for it, this can be easily done with an additional parameter: `set_attributes(., key, value, global = TRUE)` (`FALSE` by default). The problem is how to retrieve these global attributes. There are several options:

* __Request an additional argument__: Besides `function(attr)`, `function(attr, glb)` would return also global attributes. The good point here is that we don't break compatibility. On the other hand, you can retrieve arrival attributes _only_, but not global attributes only.
* __Merge attributes__: Return a union of arrival + global attributes in `attr`. I don't like this because there could be name overlapping, and that means problems.
* __Return two lists__: So that `attr["arrival"]["attr_name"]` would access arrival attributes and `attr["global"]["attr_name"] would access global attributes. This way, we solve the overlapping, but we break compatibility.
* Other ideas...?

**Comment by bart6114** [comment]
The main reason why I would consider the feature is because while a self-made monitor (like the one on the mailing list) can be easily created for a single simulation, it becomes more difficult to do this when working with replications.

My personal preference would be the first option to avoid a break in compatibility. If the feature would be included in a next major release, probably the third option is the most interesting.

I'm a bit worried about the cost of the feature in terms of performance. Especially for the third option, this would mean we should start returning a list to `attrs` and (if I'm not mistaken) we are returning a named vector now. I think we should evaluate the cost of constructing a list on the C++ side vs. a vector.

Another option would be to include a more advanced custom monitor into the package, where one can pass a key, a value and the `env` to. By passing the env we could try to distinguish between replications (possibly by the `env` name?).

**Comment by Enchufa2** [comment]
> I'm a bit worried about the cost of the feature in terms of performance.

Me too. I'll prepare a set of performance tests before continuing this discussion blindly. :)

**Comment by Enchufa2** [comment]
Check this:

``` r
library(Rcpp)
library(microbenchmark)

receive <- function(attr1 = NULL, attr2 = NULL) {
  # do nothing
}

includes = c("#include <map>", 
             "typedef std::map<std::string, double> MAP;")

cppFunction('void return_nothing(Rcpp::Function f) {
  MAP map1, map2, map3;
  map1["a"] = 1;
  map1["b"] = 2;
  map1["c"] = 3;
  map2 = map1;
  f();
}', includes=includes)

cppFunction('void return_1(Rcpp::Function f) {
  MAP map1, map2, map3;
  map1["a"] = 1;
  map1["b"] = 2;
  map1["c"] = 3;
  map2 = map1;
  f(map2);
}', includes=includes)

cppFunction('void return_2(Rcpp::Function f) {
  MAP map1, map2, map3;
  map1["a"] = 1;
  map1["b"] = 2;
  map1["c"] = 3;
  map2 = map1;
  f(map1, map2);
}', includes=includes)

cppFunction('void return_2_first_empty(Rcpp::Function f) {
  MAP map1, map2, map3;
  map1["a"] = 1;
  map1["b"] = 2;
  map1["c"] = 3;
  map2 = map1;
  f(map3, map2);
}', includes=includes)

cppFunction('void return_list(Rcpp::Function f) {
  MAP map1, map2, map3;
  map1["a"] = 1;
  map1["b"] = 2;
  map1["c"] = 3;
  map2 = map1;
  f(Rcpp::List::create(
    Rcpp::Named("first")  = map1,
    Rcpp::Named("second") = map2
    ));
}', includes=includes)

cppFunction('void return_list_first_empty(Rcpp::Function f) {
  MAP map1, map2, map3;
  map1["a"] = 1;
  map1["b"] = 2;
  map1["c"] = 3;
  map2 = map1;
  f(Rcpp::List::create(
    Rcpp::Named("first")  = map3,
    Rcpp::Named("second") = map2
    ));
}', includes=includes)

microbenchmark(return_nothing(receive),
               return_1(receive), 
               return_2(receive),
               return_2_first_empty(receive),
               return_list(receive),
               return_list_first_empty(receive), times = 10000L)
```

For me, the results are these:

```
Unit: microseconds
                             expr    min     lq     mean  median      uq      max neval
          return_nothing(receive) 20.513 24.150 26.82999 25.1390 26.2105 1879.184 10000
                return_1(receive) 22.266 25.998 28.23642 27.0965 28.1940 1877.941 10000
                return_2(receive) 22.885 26.277 28.66179 27.3635 28.5575 2017.150 10000
    return_2_first_empty(receive) 22.316 26.284 28.78185 27.3270 28.4460 1892.640 10000
             return_list(receive) 24.454 28.766 31.41242 29.9930 31.1835 2052.363 10000
 return_list_first_empty(receive) 24.557 28.594 31.14669 29.7500 30.9670 2014.259 10000
```

As expected, the first option (return an additional argument) has less overhead.

**Comment by bart6114** [comment]
Nice test.

> As expected, the first option (return an additional argument) has less overhead.

Indeed, and it doesn't break compatibility 👍

**Comment by Enchufa2** [comment]
Ok, I'll add support for global attributes following this syntax to retrieve them. :)

**Comment by Enchufa2** [comment]
Done, and [vignette updated](https://github.com/r-simmer/simmer/blob/master/vignettes/C-trajectories.Rmd#set_attribute). ;-)

**Comment by bart6114** [comment]
👍
