### ISSUE TITLE
Arrival generation cycles

### ISSUE THREAD

**Issue by Enchufa2** [r-simmer/simmer#87]
I'm moving a question by @paulorochasa from another issue to this new one with an appropriate title. The comment says:

> How can i define multiple different generators during the simulation period? What i have is a patient admission rate that is different during the day and want to reflect that in the simulation genarators.
> 
> Thank you in advance.
> BM

You have multiple options for doing this, and you don't need multiple generators necessarily:

- If you are using always the same distribution with a varying parameter, [this thread shows the way](https://groups.google.com/forum/#!msg/simmer-devel/VJlGgyLou08/Hopij5lvBAAJ):

```r
env %>%
  add_generator("patient", t0, function() rexp(1, custom_rate(now(env))))

custom_rate <- function(time) {
  # compute the desired rate as a function of the current time
}
```

- Generalising this approach is straightforward if you need different distributions for night and day, for instance:

```r
env %>%
  add_generator("patient", t0, function() custom_distribution(now(env)))

custom_distribution <- function(time) {
  # compute the desired distribution as a function of the current time
}
```

- You can do the same with a closure.
- You can dynamically change the generator function from within a trajectory using `set_distribution()` ([example](http://r-simmer.org/articles/C-trajectories.html#set_trajectory-set_distribution)).
- And of course, you can define multiple generators and dynamically control them from within a trajectory using `activate()` and `deactivate()` ([example](http://r-simmer.org/articles/C-trajectories.html#activate-deactivate)).

**Comment by paulorochasa** [comment]
Thank you Enchufa2 for you clarification and examples. This helps a lot and simplifies the script i've allready developed.
